name: Release
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: sbt ci-release
        env:
        # optional, for both sd-devops-oss & sd-devops
          CI_CLEAN: 'clean'
          CI_RELEASE: '+publish'
          CI_SNAPSHOT_RELEASE: '+publish'
        # only for sonatype oss / sd-devops-oss
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#          PGP_SECRET: ${{ secrets.PGP_SECRET }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        # only for bennuoc / sd-devops
#          NEXUS_USER: ${{ secrets.NEXUS_USER }}
#          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
