# @see https://github.com/ohze/sbt-devops/blob/main/files/sbt-devops.yml
name: sbt-devops
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      commitMsg: ${{ steps.commitMsg.outputs.msg }}
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
        prefix: [ 'sbt', 'sd' ]
        tpe: [ '', '-oss' ]
    steps:
      - uses: actions/checkout@v2
      - id: commitMsg
        run: echo "::set-output name=msg::$(git show -s --format=%s $GITHUB_SHA)"
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - uses: coursier/cache-action@v6
      - run: sbt devopsQA ${{ matrix.prefix }}-devops${{ matrix.tpe }}/test ${{ matrix.prefix }}-devops${{ matrix.tpe }}/scripted
      # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html#Caching
      - run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
        shell: bash

  publish:
    needs: build
    if: |
      success() &&
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/main' ||
        startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-20.04
    outputs:
      info: ${{ steps.info.outputs.info }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - id: info
        run: echo "::set-output name=info::$(cat "$GITHUB_WORKSPACE/target/publish.info")"

  notify:
    needs: [build, publish]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ohze/devops-notify:edge
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_PRETEXT: '@thanhpv @thanhbv xem nhé'
          _DEVOPS_NEEDS: ${{ toJSON(needs) }}
